#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$HOME/.prflow.yaml"
REPO_SLUG="${PRFLOW_GITHUB_REPO:-jopika/PRFlow}"
INSTALL_TARGET=""
TMP_DIR=""

# ── helpers ──────────────────────────────────────────────────────────────────

prompt() {
  # Must write prompt to /dev/tty and read from /dev/tty because this
  # function is called inside $() command substitution, which captures stdout.
  local question="$1"
  local default="${2:-}"
  local hint=""
  [[ -n "$default" ]] && hint=" [$default]"
  printf "%s%s: " "$question" "$hint" >/dev/tty
  read -r answer </dev/tty
  echo "${answer:-$default}"
}

prompt_choice() {
  local question="$1"
  local options="$2"   # e.g. "low/medium/high/max"
  local default="$3"
  printf "%s (%s) [%s]: " "$question" "$options" "$default" >/dev/tty
  read -r answer </dev/tty
  echo "${answer:-$default}"
}

prompt_yn() {
  local question="$1"
  local default="${2:-y}"
  local hint
  [[ "$default" == "y" ]] && hint="Y/n" || hint="y/N"
  printf "%s [%s]: " "$question" "$hint" >/dev/tty
  read -r answer </dev/tty
  answer="${answer:-$default}"
  [[ "$answer" =~ ^[Yy] ]]
}

cleanup() {
  if [[ -n "$TMP_DIR" && -d "$TMP_DIR" ]]; then
    rm -rf "$TMP_DIR"
  fi
}

require_command() {
  local cmd="$1"
  local help_text="$2"
  if ! command -v "$cmd" &>/dev/null; then
    echo "$help_text"
    exit 1
  fi
}

detect_install_target() {
  if [[ -f "$SCRIPT_DIR/pyproject.toml" ]]; then
    INSTALL_TARGET="$SCRIPT_DIR"
    return
  fi

  require_command "curl" "curl not found. Install curl first, then rerun this installer."
  require_command "python3" "python3 not found. Install Python 3.9 or newer first, then rerun this installer."

  TMP_DIR="$(mktemp -d)"
  local api_url="https://api.github.com/repos/${REPO_SLUG}/releases/latest"
  local release_json="$TMP_DIR/release.json"
  local wheel_url
  local wheel_name

  echo "Fetching latest release metadata from GitHub..."
  curl -fsSL -H "Accept: application/vnd.github+json" "$api_url" -o "$release_json"

  wheel_url="$(
    python3 - "$release_json" <<'PY'
import json
import sys

with open(sys.argv[1], "r", encoding="utf-8") as fh:
    release = json.load(fh)

for asset in release.get("assets", []):
    url = asset.get("browser_download_url", "")
    if url.endswith(".whl"):
        print(url)
        break
else:
    raise SystemExit("No wheel asset found in the latest GitHub Release.")
PY
  )"

  wheel_name="${wheel_url##*/}"
  INSTALL_TARGET="$TMP_DIR/$wheel_name"

  echo "Downloading $wheel_name..."
  curl -fsSL "$wheel_url" -o "$INSTALL_TARGET"
}

# ── install ───────────────────────────────────────────────────────────────────

trap cleanup EXIT

require_command "pipx" $'pipx not found. Install it first:\n  brew install pipx    # macOS\n  pip install pipx     # other'
detect_install_target()

if [[ "$INSTALL_TARGET" == "$SCRIPT_DIR" ]]; then
  echo "Installing prflow from local checkout..."
else
  echo "Installing prflow from the latest GitHub Release..."
fi

pipx install --force "$INSTALL_TARGET"

echo ""
echo "$(prflow --version) installed."

# ── config setup ─────────────────────────────────────────────────────────────

echo ""

if [[ -f "$CONFIG_FILE" ]]; then
  if ! prompt_yn "~/.prflow.yaml already exists. Reconfigure it?" "n"; then
    echo "Skipping config setup."
    exit 0
  fi
  echo ""
fi

echo "Setting up ~/.prflow.yaml"
echo "Press Enter to accept the default shown in [brackets]."
echo ""

# Jira
jira_url=$(prompt "Jira base URL (e.g. https://your-company.atlassian.net/browse)" "")
if [[ -z "$jira_url" ]]; then
  echo "  → Jira integration disabled (no base URL set)"
fi

echo ""

# LLM effort
effort=$(prompt_choice "LLM effort level" "low/medium/high/max" "medium")

# LLM model
model=$(prompt "Claude model override (leave blank for CLI default)" "")

echo ""

# Draft PRs
if prompt_yn "Create PRs as drafts by default?" "y"; then
  draft="true"
else
  draft="false"
fi

echo ""

# Update checks
if prompt_yn "Enable automatic update checks?" "y"; then
  updates_enabled="true"
else
  updates_enabled="false"
fi

# Protected branches
protected_raw=$(prompt "Protected branches (comma-separated)" "main,master")
IFS=',' read -ra protected_arr <<< "$protected_raw"
protected_yaml=""
for b in "${protected_arr[@]}"; do
  b="${b// /}"   # trim spaces
  protected_yaml+="  - $b"$'\n'
done

# ── write config ──────────────────────────────────────────────────────────────

{
  echo "# prflow configuration"
  echo "# Generated by install.sh — edit freely"
  echo ""

  echo "llm:"
  echo "  effort: $effort"
  [[ -n "$model" ]] && echo "  model: $model"

  echo ""
  echo "draft: $draft"

  echo ""
  echo "updates:"
  echo "  enabled: $updates_enabled"
  echo "  check_interval_hours: 24"
  echo "  github_repo: $REPO_SLUG"

  echo ""
  echo "protected_branches:"
  printf "%s" "$protected_yaml"

  if [[ -n "$jira_url" ]]; then
    echo ""
    echo "jira:"
    echo "  base_url: $jira_url"
  fi
} > "$CONFIG_FILE"

echo ""
echo "Wrote $CONFIG_FILE"
echo ""
cat "$CONFIG_FILE"
