#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$HOME/.prflow.yaml"

# ── helpers ──────────────────────────────────────────────────────────────────

prompt() {
  # Must write prompt to /dev/tty and read from /dev/tty because this
  # function is called inside $() command substitution, which captures stdout.
  local question="$1"
  local default="${2:-}"
  local hint=""
  [[ -n "$default" ]] && hint=" [$default]"
  printf "%s%s: " "$question" "$hint" >/dev/tty
  read -r answer </dev/tty
  echo "${answer:-$default}"
}

prompt_choice() {
  local question="$1"
  local options="$2"   # e.g. "low/medium/high/max"
  local default="$3"
  printf "%s (%s) [%s]: " "$question" "$options" "$default" >/dev/tty
  read -r answer </dev/tty
  echo "${answer:-$default}"
}

prompt_yn() {
  local question="$1"
  local default="${2:-y}"
  local hint
  [[ "$default" == "y" ]] && hint="Y/n" || hint="y/N"
  printf "%s [%s]: " "$question" "$hint" >/dev/tty
  read -r answer </dev/tty
  answer="${answer:-$default}"
  [[ "$answer" =~ ^[Yy] ]]
}

# ── install ───────────────────────────────────────────────────────────────────

if ! command -v pipx &>/dev/null; then
  echo "pipx not found. Install it first:"
  echo "  brew install pipx    # macOS"
  echo "  pip install pipx     # other"
  exit 1
fi

if pipx list --short 2>/dev/null | grep -q "^prflow "; then
  echo "Reinstalling prflow..."
  pipx reinstall prflow
else
  echo "Installing prflow..."
  pipx install "$SCRIPT_DIR"
fi

echo ""
echo "$(prflow --version) installed."

# ── config setup ─────────────────────────────────────────────────────────────

echo ""

if [[ -f "$CONFIG_FILE" ]]; then
  if ! prompt_yn "~/.prflow.yaml already exists. Reconfigure it?" "n"; then
    echo "Skipping config setup."
    exit 0
  fi
  echo ""
fi

echo "Setting up ~/.prflow.yaml"
echo "Press Enter to accept the default shown in [brackets]."
echo ""

# Jira
jira_url=$(prompt "Jira base URL (e.g. https://your-company.atlassian.net/browse)" "")
if [[ -z "$jira_url" ]]; then
  echo "  → Jira integration disabled (no base URL set)"
fi

echo ""

# LLM effort
effort=$(prompt_choice "LLM effort level" "low/medium/high/max" "medium")

# LLM model
model=$(prompt "Claude model override (leave blank for CLI default)" "")

echo ""

# Draft PRs
if prompt_yn "Create PRs as drafts by default?" "y"; then
  draft="true"
else
  draft="false"
fi

# Protected branches
protected_raw=$(prompt "Protected branches (comma-separated)" "main,master")
IFS=',' read -ra protected_arr <<< "$protected_raw"
protected_yaml=""
for b in "${protected_arr[@]}"; do
  b="${b// /}"   # trim spaces
  protected_yaml+="  - $b"$'\n'
done

# ── write config ──────────────────────────────────────────────────────────────

{
  echo "# prflow configuration"
  echo "# Generated by install.sh — edit freely"
  echo ""

  echo "llm:"
  echo "  effort: $effort"
  [[ -n "$model" ]] && echo "  model: $model"

  echo ""
  echo "draft: $draft"

  echo ""
  echo "protected_branches:"
  printf "%s" "$protected_yaml"

  if [[ -n "$jira_url" ]]; then
    echo ""
    echo "jira:"
    echo "  base_url: $jira_url"
  fi
} > "$CONFIG_FILE"

echo ""
echo "Wrote $CONFIG_FILE"
echo ""
cat "$CONFIG_FILE"
